### PR TITLE
Cards dnd bug

### PR DESCRIPTION
**Pull request by DanNisenson**
Fixed bug when moving cards.
Moving a card worked the first time but after moving, it didn't get it's position right when operating with the element.
added props.position to dependencies in both drag and drop hooks and swapped card info retrieval from context.cards to props.listCards

### CODE REVIEW

**Review by eduardpeters — APPROVED** [review]
Great news! Can we do a quick commit to remove the console.logs and check if the index in the Cards map is required or if we can leave only Card as argument for that one?

**Comment by DanNisenson** [comment]
sure, Im trying to clean all of SingleCard props. I'll talk to Carlos and make a new clean commit

**Comment by DanNisenson** [comment]
merged current main into this branch so there's no conflicts.
fixed displaying right amount of cards in MoveCard menu when moving in the list where it's currently at.
Tested all i could think of.
Rounded off a little bit of styling here and there

**Review by carlosisen — APPROVED** [review]
Gran trabajo dan!
Genial el destructuring de las props y todo lo demás.  Un currazo todo.

**Pull request merged**
